# Generated by Django 5.0.6 on 2024-08-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='balance_after_transaction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
